# Generated by Django 5.1.7 on 2025-03-23 13:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_cartitem_order_orderitem_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(default='Black', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='clothing',
            name='availability_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('coming_soon', 'Coming Soon')], default='in_stock', max_length=20),
        ),
        migrations.AddField(
            model_name='clothing',
            name='available_colors',
            field=models.CharField(blank=True, default='Black,White', help_text="Comma separated colors (e.g. 'Red,Blue,Black')", max_length=100),
        ),
        migrations.AddField(
            model_name='clothing',
            name='available_sizes',
            field=models.CharField(blank=True, default='S,M,L,XL', help_text="Comma separated sizes (e.g. 'S,M,L,XL')", max_length=100),
        ),
        migrations.AddField(
            model_name='clothing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clothing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clothes.clothing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
